version: "2"
services:

  node-server:
    build:
      context: app
    ports:
      - 8080:8080
#    command: "nodemon ./src/index.js"
    command: bash /start.sh
    depends_on:
      - postgresdb
    volumes:
      - ./node_modules:/usr/src/app/node_modules
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=test
      - POSTGRES_HOST=postgresdb
      - POSTGRES_PORT=543
  
  postgresdb:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=test
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
      
  nginx:
#    image: nginx:1.11.6
    build: 
      context: ./nginx/
#    volumes:
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#       - ./prodobavki.com/:/var/www/html/:ro
#       - /nginxcache/:/etc/nginx/cache/
#       - ./certs/letsencrypt/:/certs/
    ports:
       - "80:80"
       - "443:443"
    links:
      - node-server
    restart: always
