version: "2"
services:
#  node-test:
#    build:
#      context: node-test
      
  node-server:
    build:
      context: ./
    ports:
      - 8080:8080
#    command: "node -i && nodemon ./src/index.js"
    command: bash /start.sh
    depends_on:
      - postgresdb
    volumes:
      - ./node_modules:/usr/src/app/node_modules
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=test
      - POSTGRES_HOST=postgresdb
      - POSTGRES_PORT=5432
      - PORT=8080
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - MESSAGE=app
  
  postgresdb:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=test
    volumes:
      - ./data:/var/lib/postgresql/data
      
  nginx:
#    image: nginx:1.11.6
    build: 
      context: ./nginx/
#    volumes:
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#       - ./prodobavki.com/:/var/www/html/:ro
#       - /nginxcache/:/etc/nginx/cache/
#       - ./certs/letsencrypt/:/certs/
    depends_on:
      - node-server
    ports:
       - "80:80"
       - "443:443"
    links:
      - node-server
#    logging:
#        driver: syslog
    restart: always
